import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import {Button} from '@chakra-ui/react'
import SliderTeam from '../components/slide'
import CardGrid from '../components/cardgrid'
import NavHero from '../components/nav'
import { Box } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHero />
      <Box mt={20}>
        <SliderTeam />
        <CardGrid />
      </Box>
    </div>
  )
}

export default Home;