import Head from 'next/head'
import { FormLogin } from "src/container"
// import { Header } from "@/components/index";

const Login = () => {
  return (
    <>
      <Head>
        <title>Crânio | Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FormLogin />
    </>
  );
};

export default Login